### ISSUE TITLE
Pystrum is incompatible with `numpy==1.24` due to `AttributeError` from now-removed `np.bool`

### ISSUE THREAD

**Issue by joshuacwnewton** [adalca/pytools-lib#9]
The usage of `np.bool` is here:

https://github.com/adalca/pystrum/blob/8cd5c483195971c0c51e9809f33aa04777aa35c8/pystrum/pynd/ndutils.py#L581

`np.bool` was removed in [`numpy==1.24`](https://github.com/numpy/numpy/releases/tag/v1.24.0):

> The deprecation for the aliases np.object, np.bool, np.float,
np.complex, np.str, and np.int is expired (introduces NumPy
1.20). Some of these will now give a FutureWarning in addition to
raising an error since they will be mapped to the NumPy scalars in
the future. (https://github.com/numpy/numpy/pull/22607)

When importing `pystrum` (or even importing downstream dependencies like `neurite`), the following error will be thrown:

```python
  File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/voxelmorph/__init__.py", line 12, in <module>
    import neurite
  File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/neurite/__init__.py", line 19, in <module>
    import pystrum
  File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pystrum/__init__.py", line 3, in <module>
    from . import pynd
  File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pystrum/pynd/__init__.py", line 1, in <module>
    from . import ndutils
  File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/pystrum/pynd/ndutils.py", line 581, in <module>
    def sphere_vol(vol_shape, radius, center=None, dtype=np.bool):
  File "/home/runner/work/spinalcordtoolbox/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
```

As for how to fix this issue: `np.bool` is just an alias to the built-in `bool` type. _(More information about the deprecation can be found [here](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).)_

**Comment by adalca** [comment]
seems fixed now with @mu40 's PR, right?

**Comment by joshuacwnewton** [comment]
Thanks much for the prompt response! :hearts: 

> seems fixed now with @mu40 's PR, right?

Yes and no? It's fixed on `master`, but until a new version of `pystrum` is released to PyPI, `pip`-based installs (i.e. `pystrum==0.2`) will still encounter this error.

(Right now, in our project, we're pinning `numpy<1.24` to mitigate this issue, but ideally we would instead be pinning `pystrum>=0.3` or something similar.)
